[tool.poetry]
name = 'Sauceify'
version = '1.2.3'
description = 'sauce'

[tool.poetry.dependencies]
python = '^3.6'
django = '4.2.3'

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'