[tool.poetry]
name = 'Sauceify'
version = '1.2.3'
description = 'sauce'
authors = ['me']

[tool.poetry.dependencies]
python = '>=3.8,<4.0'
django = '^4.2.3'
environ = '^0.9.0'

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'