databases:
  - name: sauceify
    databaseName: sauceify
    user: sauceify

services:
  - type: web
    name: sauceify
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sauceify.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sauceify
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4