# Generated by Django 4.2.2 on 2023-07-03 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_sauce_food_sauce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='img',
        ),
        migrations.AlterField(
            model_name='food',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='main_app.sauce'),
        ),
    ]
